# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: pedrohlucena
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: backend-letalk-challenge
service: backend-letalk-challenge

provider:
  name: aws
  runtime: nodejs20.x
  stage: v1
  region: us-east-2
  timeout: 30
  memorySize: 512
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .vscode/**
      
  environment:
    MONGODB_CONNECTION_STR: ${param:mongodbConnectionStr}
    DB_NAME: ${param:dbName}
    NODE_ENV: ${param:nodeEnv}

functions:
  app:
    handler: handler.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline      